---
heat_template_version: 2017-09-01

description: Sample Nova Server Template

parameters:
  default_mtu:
    type: string
    default: 1450

resources:
  sample_network:
    type: OS::Neutron::Net
    properties:
      tags:
        - test
      value_specs:
        mtu: { get_param: default_mtu }

  sample_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: sample_network }
      cidr: 192.168.20.0/24
      dns_nameservers: [114.114.114.114]

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: 
        network: floating-network
  
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: sample_subnet }
  
  router_server_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network:	floating-network

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: router_interface
    properties:
      floatingip_id: { get_resource: router_server_fip }
      port_id: { get_resource: iperf_server_port }

  iperf_server_port:
      type: OS::Neutron::Port
      properties:
        network: { get_resource: sample_network }

  sample_iperf_server:
    type: OS::Nova::Server
    properties:
      name: sjt-test-heat
      image: 45055dda-b34b-4c4d-b5cf-84b137fe04b7
      flavor: southtest-2C2G40G
      networks:
        - port: { get_resource: iperf_server_port }
      key_name: like

  sample_iperf_client:
    type: OS::Nova::Server
    properties:
      name: sjt-test-heat
      image: 45055dda-b34b-4c4d-b5cf-84b137fe04b7
      flavor: southtest-2C2G40G
      networks:
        - network: { get_resource: sample_network }
      key_name: like

outputs:
  single_console_url:
    value: { get_attr: [sample_iperf_server, console_urls, novnc] }
    description: console URL for server
