---
heat_template_version: 2017-09-01

description: Sample Nova Server Template

parameters:
  default_mtu:
    type: string
    default: 1450


resources:

  sample_network:
    type: OS::Neutron::Net
    properties:
      tags:
        - test
      value_specs:
        mtu: { get_param: default_mtu }

  sample_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: sample_network }
      cidr: 192.168.22.0/24
      dns_nameservers: [114.114.114.114]

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: 
        network: floating-network
  
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: sample_subnet }
  
  router_server_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: floating-network

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: router_interface
    properties:
      floatingip_id: { get_resource: router_server_fip }
      port_id: { get_resource: iperf_server_port }

  iperf_server_port:
      type: OS::Neutron::Port
      properties:
        network: { get_resource: sample_network }
        fixed_ips:
          - ip_address: 192.168.22.10
  
  cloud_init_userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: { get_resource: router_server_config }

  router_server_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config: 
        package_update: true
        package_upgrade: true
        packages:
          - salt-master
          - reclass
        salt_minion:
          pkg_name: 'salt-minion'
          service_name: 'salt-minion'
          config_dir: '/etc/salt'
          conf:
              master: 192.168.22.10
        ssh_pwauth: true
        users:
          - default
          - name: sjt
            passwd: $1$xyz$X11iz6ox24iPDed6detyU.
            lock_passwd: false
            groups: users, admin
            sudo: ALL=(ALL) NOPASSWD:ALL
            home: /home/sjt
            shell: /bin/bash
        write_files:
          - path: /etc/salt/master.d/master.conf
            content: |
              auto_accept: True
              file_roots:
                  base:
                      - /srv/salt
              pillar_roots:
                  base:
                      - /srv/pillar
          - path: /srv/pillar/top.sls
            content: |
              base:
                "*server*":
                  - server
                "*slave*":
                  - slave
          - path: /srv/salt/top.sls
            content: |
              base:
                "*server*":
                  - server
                "*slave*":
                  - slave
        runcmd:
          - wget https://iperf.fr/download/ubuntu/libiperf0_3.1.3-1_amd64.deb
          - wget https://iperf.fr/download/ubuntu/iperf3_3.1.3-1_amd64.deb
          - sudo dpkg -i libiperf0_3.1.3-1_amd64.deb iperf3_3.1.3-1_amd64.deb
          - sudo mkdir -p /srv/salt
          - sudo mkdir -p /salt/pillar

  sample_iperf_server:
    type: OS::Nova::Server
    properties:
      name: sjt-test-server
      image: 45055dda-b34b-4c4d-b5cf-84b137fe04b7
      flavor: IPERF_SERVER_6C6G40G
      networks:
        - port: { get_resource: iperf_server_port }
      key_name: like
      user_data: { get_resource: cloud_init_userdata }
      user_data_format: SOFTWARE_CONFIG

  slave_resources:
    type: OS::Heat::ResourceGroup
    properties:
      count: 6
      resource_def:
        type: OS::Nova::Server
        properties:
          image: 45055dda-b34b-4c4d-b5cf-84b137fe04b7
          flavor: southtest-2C2G40G
          networks:
            - network: { get_resource: sample_network }
          user_data: { get_resource: cloud_init_userdata }
          user_data_format: SOFTWARE_CONFIG
          key_name: like

outputs:
  single_console_url:
    value: { get_attr: [sample_iperf_server, console_urls, novnc] }
    description: console URL for server